spring:
  application:
    name: ev-carbon-monitor
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080
  servlet:
    context-path: /api


logging:
  level:
    root: INFO
    com.example.evcarbonmonitor: DEBUG
