spring:
  application:
    name: ev-carbon-monitor
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/evcarbonmonitor
  #   username: ${USER}
  #   password: ""
  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.PostgreSQLDialect
  #   show-sql: true

server:
  port: 8080
  servlet:
    context-path: /api

# blockchain:
#   web3-provider: http://localhost:8545

logging:
  level:
    root: INFO
    com.example.evcarbonmonitor: DEBUG
